### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by newca12** [edomora97/noir#1]
Great work.
Which license is noir source code published under ?

**Comment by edomora97** [comment]
Thanks and sorry for the late reply!

This has been the work for ours (@mdonadoni's and mine) master's degree thesis at Politecnico di Milano. This repository is very unmaintained at the moment, and we didn't think about choosing a license for it. However, you can find a fork with more features and bug fixes here: https://github.com/deib-polimi/noir
That repository includes a license for the code, and you can rely on that!
